apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: mysql-pv-claim
spec: 
  accessModes: 
    - ReadWriteOnce 
  storageClassName: manual   #bunun Pv ile aynı olması lazım. 
  resources: 
    requests: 
      storage: 1Gi