apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql-server
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-pod
  template:
    metadata:
      labels:
        app: mysql-pod
    spec:
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      containers:
      - name: mysql
        image: mysql:5.7
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /data/mysql
          name: mysql-storage
        env:     # bunları secretten alıyoruz.
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysqlsecret
              key: mysql-admin-pass
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysqlsecret
              key: mysql-root-pass
        - name: MySQL_USER
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: MySQL_USER
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: MYSQL_DATABASE
        - name: MYSQL_DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: MYSQL_DATABASE_HOST          
