apiVersion: v1   # version 
kind: Service    # object çeşiti
metadata:
  name: result-server-svc # isim verdik
  labels:
    name: result-server
spec:         # service in tipi clusterip
  type: Nodeport 
  ports:
  - name: http   
    port: 80       
    targetPort: 80
    nodePort: 30002
  selector:
    name: result-server   # service pod u buradan bulacak
