apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume   # pv ye isim verdik 
  labels:
    type: local   # sdece bir label verdik
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:             # tipi
    path: "/mnt/data"   # bu podun çalıştığı node un mnt klasoru altında data klasoru