apiVersion: v1
kind: Service
metadata:
  labels:
    app: result-server-deploy
  name: result-server-deploy
spec:
  ports:
  - port: 80    # service in portu
    protocol: TCP
    targetPort: 80   # container portu
    nodePort: 30002  #nodeporttan dışarı çıkış biri 30001 diğeri 2 oldu
  selector:
    app: result-server-deploy   # result deploydaki template labelı aynı
  type: NodePort