apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  selector: 
    app: mysql-pod  #db deploymenttaki pod ismi
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
